from io import BytesIO
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Preformatted
)
from reportlab.lib.styles import getSampleStyleSheet
from xml.sax.saxutils import escape


# =====================================================
# PDF TITLES
# =====================================================

PDF_TITLES = {
    "notes": "NCF 2023 Study Notes",
    "mcq": "NCF 2023 Competency Based MCQ Sheet",
    "question_paper": "NCF 2023 Question Paper",
    "lesson_plan": "NCF 2023 Lesson Plan",
    "teaching_guide": "NCF 2023 Teaching Guide",
    "learning_outcomes": "NCF 2023 Learning Outcomes",
    "competencies": "NCF 2023 Competencies",
    "flowchart": "NCF 2023 Flow Chart",
    "mindmap": "NCF 2023 Mind Map",
    "chapter_summary": "NCF 2023 Chapter Summary",
    "important_questions": "NCF 2023 Important Questions"
}


# =====================================================
# MAIN PDF GENERATOR
# =====================================================

def generate_pdf(
    title,
    content,
    source="Uploaded Document"
):

    try:

        buffer = BytesIO()

        doc = SimpleDocTemplate(buffer)

        styles = getSampleStyleSheet()

        title_style = styles["Title"]
        heading_style = styles["Heading2"]
        body_style = styles["BodyText"]

        story = []

        # Title

        story.append(
            Paragraph(
                escape(str(title)),
                title_style
            )
        )

        story.append(
            Spacer(1, 15)
        )

        # Content

        if (
            content is None
            or
            str(content).strip() == ""
        ):
            content = "No content generated."

        story.append(
            Preformatted(
                escape(str(content)),
                body_style
            )
        )

        story.append(
            Spacer(1, 20)
        )

        # Source

        story.append(
            Paragraph(
                "Source Information",
                heading_style
            )
        )

        story.append(
            Paragraph(
                escape(str(source)),
                body_style
            )
        )

        story.append(
            Spacer(1, 20)
        )

        # Footer

        story.append(
            Paragraph(
                "Generated by NCF 2023 AI Teacher Assistant",
                body_style
            )
        )

        doc.build(story)

        pdf_bytes = buffer.getvalue()

        buffer.close()

        return pdf_bytes

    except Exception as e:

        return (
            f"PDF Generation Error: {e}"
        ).encode()


# =====================================================
# GENERIC PDF CREATOR
# =====================================================

def create_pdf(
    pdf_type,
    content,
    source
):

    return generate_pdf(
        PDF_TITLES.get(
            pdf_type,
            "NCF 2023 AI Teacher Assistant"
        ),
        content,
        source
    )


# =====================================================
# NOTES PDF
# =====================================================

def notes_pdf(notes, source):

    return create_pdf(
        "notes",
        notes,
        source
    )


# =====================================================
# MCQ PDF
# =====================================================

def mcq_pdf(mcqs, source):

    return create_pdf(
        "mcq",
        mcqs,
        source
    )


# =====================================================
# QUESTION PAPER PDF
# =====================================================

def question_paper_pdf(
    paper,
    source
):

    return create_pdf(
        "question_paper",
        paper,
        source
    )


# =====================================================
# LESSON PLAN PDF
# =====================================================

def lesson_plan_pdf(
    lesson_plan,
    source
):

    return create_pdf(
        "lesson_plan",
        lesson_plan,
        source
    )


# =====================================================
# TEACHING GUIDE PDF
# =====================================================

def teaching_guide_pdf(
    guide,
    source
):

    return create_pdf(
        "teaching_guide",
        guide,
        source
    )


# =====================================================
# LEARNING OUTCOMES PDF
# =====================================================

def learning_outcomes_pdf(
    content,
    source
):

    return create_pdf(
        "learning_outcomes",
        content,
        source
    )


# =====================================================
# COMPETENCIES PDF
# =====================================================

def competencies_pdf(
    content,
    source
):

    return create_pdf(
        "competencies",
        content,
        source
    )


# =====================================================
# FLOWCHART PDF
# =====================================================

def flowchart_pdf(
    content,
    source
):

    return create_pdf(
        "flowchart",
        content,
        source
    )


# =====================================================
# MINDMAP PDF
# =====================================================

def mindmap_pdf(
    content,
    source
):

    return create_pdf(
        "mindmap",
        content,
        source
    )


# =====================================================
# CHAPTER SUMMARY PDF
# =====================================================

def chapter_summary_pdf(
    content,
    source
):

    return create_pdf(
        "chapter_summary",
        content,
        source
    )


# =====================================================
# IMPORTANT QUESTIONS PDF
# =====================================================

def important_questions_pdf(
    content,
    source
):

    return create_pdf(
        "important_questions",
        content,
        source
    )
