from io import BytesIO
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    PageBreak,
    Preformatted
)
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib import colors
from xml.sax.saxutils import escape


def generate_pdf(
    title,
    content,
    source="Uploaded Document"
):

    buffer = BytesIO()

    doc = SimpleDocTemplate(buffer)

    styles = getSampleStyleSheet()

    story = []

    title_style = styles["Title"]
    heading_style = styles["Heading2"]
    body_style = styles["BodyText"]

    # -----------------------------
    # Title
    # -----------------------------
    story.append(
        Paragraph(
            escape(title),
            title_style
        )
    )

    story.append(
        Spacer(1, 15)
    )

    # -----------------------------
    # Empty Content Check
    # -----------------------------
    if not content or str(content).strip() == "":

        content = "No content generated."

    # -----------------------------
    # Main Content
    # -----------------------------
    content = str(content)

    content = escape(content)

    story.append(
        Preformatted(
            content,
            body_style
        )
    )

    story.append(
        Spacer(1, 20)
    )

    # -----------------------------
    # Source
    # -----------------------------
    story.append(
        Paragraph(
            "Source Information",
            heading_style
        )
    )

    story.append(
        Paragraph(
            escape(source),
            body_style
        )
    )

    story.append(
        Spacer(1, 20)
    )

    # -----------------------------
    # Footer
    # -----------------------------
    story.append(
        Paragraph(
            "Generated by AI Teacher Assistant",
            body_style
        )
    )

    doc.build(story)

    pdf_bytes = buffer.getvalue()

    buffer.close()

    return pdf_bytes


# =====================================
# NOTES PDF
# =====================================

def notes_pdf(notes, source):
    return generate_pdf(
        "Study Notes",
        notes,
        source
    )


# =====================================
# MCQ PDF
# =====================================

def mcq_pdf(mcqs, source):
    return generate_pdf(
        "MCQ Sheet",
        mcqs,
        source
    )


# =====================================
# QUESTION PAPER PDF
# =====================================

def question_paper_pdf(paper, source):
    return generate_pdf(
        "Question Paper",
        paper,
        source
    )


# =====================================
# LESSON PLAN PDF
# =====================================

def lesson_plan_pdf(lesson_plan, source):
    return generate_pdf(
        "Lesson Plan",
        lesson_plan,
        source
    )


# =====================================
# TEACHING GUIDE PDF
# =====================================

def teaching_guide_pdf(guide, source):
    return generate_pdf(
        "Teaching Guide",
        guide,
        source
    )
