from io import BytesIO
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    PageBreak
)
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib import colors


def generate_pdf(
    title,
    content,
    source="Uploaded Document"
):
    """
    Generate PDF and return bytes.
    """

    buffer = BytesIO()

    doc = SimpleDocTemplate(buffer)

    styles = getSampleStyleSheet()

    story = []

    title_style = styles["Title"]
    heading_style = styles["Heading2"]
    body_style = styles["BodyText"]

    # -----------------------------
    # Title
    # -----------------------------
    story.append(
        Paragraph(title, title_style)
    )

    story.append(Spacer(1, 12))

    # -----------------------------
    # Content
    # -----------------------------
    lines = content.split("\n")

    for line in lines:

        line = line.strip()

        if not line:
            continue

        story.append(
            Paragraph(line, body_style)
        )

        story.append(
            Spacer(1, 4)
        )

    story.append(Spacer(1, 20))

    # -----------------------------
    # Source Section
    # -----------------------------
    story.append(
        Paragraph(
            "Source Information",
            heading_style
        )
    )

    story.append(
        Paragraph(
            source,
            body_style
        )
    )

    story.append(
        Spacer(1, 12)
    )

    # -----------------------------
    # Footer
    # -----------------------------
    story.append(
        Paragraph(
            "Generated by AI Teacher Assistant",
            body_style
        )
    )

    doc.build(story)

    pdf = buffer.getvalue()

    buffer.close()

    return pdf


# -------------------------------------
# Notes PDF
# -------------------------------------

def notes_pdf(
    notes,
    source
):
    return generate_pdf(
        title="Study Notes",
        content=notes,
        source=source
    )


# -------------------------------------
# MCQ PDF
# -------------------------------------

def mcq_pdf(
    mcqs,
    source
):
    return generate_pdf(
        title="MCQ Sheet",
        content=mcqs,
        source=source
    )


# -------------------------------------
# Question Paper PDF
# -------------------------------------

def question_paper_pdf(
    paper,
    source
):
    return generate_pdf(
        title="Question Paper",
        content=paper,
        source=source
    )


# -------------------------------------
# Lesson Plan PDF
# -------------------------------------

def lesson_plan_pdf(
    lesson_plan,
    source
):
    return generate_pdf(
        title="Lesson Plan",
        content=lesson_plan,
        source=source
    )


# -------------------------------------
# Teaching Guide PDF
# -------------------------------------

def teaching_guide_pdf(
    guide,
    source
):
    return generate_pdf(
        title="Teaching Guide",
        content=guide,
        source=source
    )
